#!/bin/bash
# Remove all unused packages
echo '🗑️  Removing all unused packages...'
source /Users/danielchayes/ai-assistant/venv/bin/activate
pip uninstall -y contourpy orjson confection pyobjc-framework-uniformtypeidentifiers pyobjc-framework-netfs bnunicodenormalizer pyobjc-framework-mediaaccessibility pyobjc-framework-iosurface pyobjc-framework-cryptotokenkit thinc pyobjc-framework-contacts pyobjc-framework-kernelmanagement black multidict bnnumerizer cython pyobjc-framework-imagecapturecore cymem pyobjc-framework-callkit flake8
pip uninstall -y httpx-sse threadpoolctl bangla trainer tokenizers pyobjc-framework-backgroundassets pyobjc-framework-mailkit babel language_data pyobjc-framework-mapkit huggingface-hub pyobjc-framework-metalfx optimum pyobjc-framework-corewlan pyobjc-framework-symbols pyobjc-framework-coreml srsly build posthog mmh3
pip uninstall -y pyobjc-framework-multipeerconnectivity pyobjc-framework-screentime weasel pyobjc-framework-modelio flatbuffers humanfriendly pyaudio pyobjc-framework-sensitivecontentanalysis pyobjc-framework-speech attrs pyobjc-framework-instantmessage pyobjc-framework-systemextensions pyobjc-framework-cinematic pypika requests-oauthlib python-crfsuite regex pyobjc-framework-localauthentication dateparser spacy-loggers
pip uninstall -y accelerate pyobjc-core opentelemetry-instrumentation flask audioread mpmath pyobjc-framework-opendirectory pyobjc-framework-coretext safehttpx marisa-trie click pyobjc-framework-mediatoolbox opentelemetry-api pyobjc-framework-searchkit pyobjc-framework-mediaplayer typing_extensions gruut_lang_es pyobjc-framework-calendarstore sqlite-vec pyobjc-framework-metal
pip uninstall -y pyparsing lazy_loader pyobjc-framework-naturallanguage joblib nltk pypinyin tensorboard-data-server einops pyobjc-framework-metalkit pyobjc-framework-eventkit googleapis-common-protos pyobjc-framework-avkit pyobjc-framework-notificationcenter pyobjc-framework-fileprovider pyobjc-framework-libdispatch pyobjc-framework-fskit gruut-ipa tomlkit pyobjc-framework-colorsync uvloop
pip uninstall -y pyobjc-framework-corespotlight hf-xet typeguard pyflakes pyobjc-framework-coreaudio pycodestyle spacy pyobjc-framework-automaticassessmentconfiguration yarl pyobjc-framework-adservices pyobjc-framework-applicationservices cloudpathlib hangul-romanize pyobjc-framework-linkpresentation smart-open pyobjc-framework-fileproviderui pyobjc-framework-iobluetooth pyobjc-framework-browserenginekit pycparser pyobjc-framework-threadnetwork
pip uninstall -y platformdirs pyobjc-framework-devicediscoveryextension pydantic_core umap-learn httpcore annotated-types opentelemetry-exporter-otlp-proto-common pyobjc-framework-launchservices pyobjc-framework-audiovideobridging fonttools pyobjc-framework-corebluetooth mypy_extensions soundfile oauthlib pyobjc-framework-network pyobjc-framework-phase nodeenv gruut_lang_de sse-starlette pydantic-settings
pip uninstall -y sniffio cycler chromadb pyobjc-framework-avfoundation websocket-client mcp scipy blis pyobjc-framework-accounts pyobjc-framework-applescriptobjc pyobjc-framework-syncservices torch pyobjc-framework-metrickit pyobjc-framework-security pyobjc-framework-extensionkit pyobjc-framework-gamekit python-multipart pyobjc-framework-coremotion pynndescent pyobjc-framework-gamecontroller
pip uninstall -y opentelemetry-instrumentation-fastapi pyobjc-framework-carbon pyobjc-framework-preferencepanes websockets cffi preshed wasabi jsonlines g2pkk pyobjc-framework-photos pyobjc-framework-apptrackingtransparency pyobjc-framework-coreaudiokit pyobjc-framework-networkextension opentelemetry-instrumentation-asgi pyobjc-framework-fsevents importlib_resources pyobjc-framework-shazamkit decorator pluggy aiosignal
pip uninstall -y pyproject_hooks kubernetes num2words networkx virtualenv pyobjc-framework-sharedwithyou identify pyobjc-framework-oslog pyobjc-framework-adsupport durationpy pyobjc-framework-coremidi pyobjc-framework-dictionaryservices pyobjc-framework-soundanalysis anyascii pyobjc-framework-coredata pyobjc-framework-classkit google-auth pyobjc-framework-mediaextension opentelemetry-sdk pyobjc-framework-findersync
pip uninstall -y watchfiles aiohappyeyeballs rich pyobjc-framework-pencilkit llvmlite safetensors frozenlist jieba pre_commit catalogue pyobjc-framework-corehaptics pyobjc pyobjc-framework-intentsui pyasn1_modules pyobjc-framework-cocoa pyobjc-framework-installerplugins semantic-version pyobjc-framework-executionpolicy gtts kiwisolver
pip uninstall -y backoff anyio gruut pyobjc-framework-cloudkit edge-tts pyobjc-framework-localauthenticationembeddedui coqpit tenacity pooch matplotlib opentelemetry-exporter-otlp-proto-grpc pyobjc-framework-photosui pyobjc-framework-gamecenter pyobjc-framework-videotoolbox typing-inspection pyobjc-framework-healthkit pyobjc-framework-systemconfiguration pyobjc-framework-metalperformanceshaders pysbd langcodes
pip uninstall -y grpcio markdown pyobjc-framework-dvdplayback opentelemetry-proto pyobjc-framework-inputmethodkit pyasn1 murmurhash tzdata pyobjc-framework-scriptingbridge pyobjc-framework-safariservices pyobjc-framework-safetykit ruff pyobjc-framework-screensaver pyobjc-framework-spritekit pyobjc-framework-diskarbitration tqdm pyobjc-framework-exceptionhandling ffmpy opentelemetry-util-http unidecode
pip uninstall -y pyobjc-framework-quicklookthumbnailing pyobjc-framework-securityui spacy-legacy bcrypt alembic pyobjc-framework-videosubscriberaccount pydub pyobjc-framework-securityinterface pillow pyobjc-framework-devicecheck markdown-it-py pyobjc-framework-storekit wrapt pyobjc-framework-metalperformanceshadersgraph h11 sympy tiktoken zipp librosa pyobjc-framework-externalaccessory
pip uninstall -y pyobjc-framework-ituneslibrary httptools pyobjc-framework-applescriptkit overrides pyobjc-framework-sharedwithyoucore pyobjc-framework-scenekit inflect tzlocal pyobjc-framework-coreservices torchaudio pyobjc-framework-automator pygments aiofiles pyobjc-framework-libxpc pyobjc-framework-medialibrary pyobjc-framework-pushkit mypy docopt pyobjc-framework-corelocation pyobjc-framework-datadetection
pip uninstall -y pyobjc-framework-securityfoundation pyobjc-framework-passkit tensorboard gruut_lang_en gruut_lang_fr aiohttp pathspec cfgv pyobjc-framework-addressbook coloredlogs chroma-hnswlib mdurl pyobjc-framework-usernotificationsui shellingham pyobjc-framework-mlcompute typer pyobjc-framework-businesschat pyobjc-framework-servicemanagement cachetools pyobjc-framework-social
pip uninstall -y importlib_metadata absl-py gradio_client iniconfig pyobjc-framework-usernotifications pyobjc-framework-webkit sudachidict-core ollama pyobjc-framework-coremedia pyobjc-framework-avrouting propcache mako transformers pyobjc-framework-cfnetwork soxr pyobjc-framework-discrecording jamo pyobjc-framework-discrecordingui pyobjc-framework-collaboration pyobjc-framework-intents
pip uninstall -y pyobjc-framework-coremediaio onnxruntime pyobjc-framework-gameplaykit pyobjc-framework-authenticationservices pyobjc-framework-iobluetoothui pyobjc-framework-screencapturekit rsa protobuf pyobjc-framework-osakit mccabe pyobjc-framework-vision pyobjc-framework-virtualization pyobjc-framework-contactsui numba pyobjc-framework-latentsemanticmapping pyobjc-framework-replaykit opentelemetry-semantic-conventions encodec asgiref pyobjc-framework-accessibility
pip uninstall -y more-itertools msgpack sudachipy pyobjc-framework-quartz
echo '✅ Deep cleanup complete!'
pip list | wc -l
